### ISSUE TITLE
0.6.2 tarball gives 500 error on pecl page

### ISSUE THREAD

**Issue by glensc** [derickr/pecl-translit#4]
pecl page lists 0.6.2
- https://pecl.php.net/package/translit

but it's 404:
- https://pecl.php.net/get/translit-0.6.2.tgz
- http://pecl.php.net/get/translit-0.6.2.tgz

**Comment by glensc** [comment]
the server gives now 500 error for both urls

**Comment by glensc** [comment]
@derickr ping

**Comment by derickr** [comment]
That's true, but there is 0.6.3 which you should be using. I can only fix this by removing the 0.6.2 release.

**Comment by derickr** [comment]
Closing this out, as 0.6.3 (and soon 0.6.4) is what you should use.
