### ISSUE TITLE
0.6.3 pecl tarball doesn't contain tests

### ISSUE THREAD

**Issue by glensc** [derickr/pecl-translit#5]
```
wget https://pecl.php.net/get/translit-0.6.3.tgz --no-check-certificate
tar tvf translit-0.6.3.tgz|grep tests -c
0
```

**Comment by derickr** [comment]
PECL translit never shipped with tests, so this is not a bug. Feel free to submit a PR to add them to the package.`xml` file

**Comment by glensc** [comment]
what is the recommendation then? (Linux) distributions should use GitHub generated tarball rather PECL upload?

**Comment by derickr** [comment]
No, they should use the latest (0.6.3) PECL release :-)

**Comment by glensc** [comment]
but then they can't run tests in build process, should download tests from alternative tarball?

**Comment by derickr** [comment]
They should be part of the tarball., hence the: enhancement, and "help wanted" tags for this issue.
